# Generated by Django 5.0.4 on 2025-06-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblisting', '0003_careerpath_alter_cvupload_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='extracted_skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='skills',
            field=models.ManyToManyField(related_name='job_listings', to='joblisting.skill'),
        ),
    ]
